apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksexample-87a7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksexample-87a7"
  template:
    metadata:
      labels:
        app: "aksexample-87a7"
    spec:
      containers:
        - name: "aksexample-87a7"
          image: "aksnodejs.azurecr.io/aksexample"
          ports:
          - containerPort: 3000