apiVersion: v1
kind: Service
metadata:
    name: "aksexample-87a7"
    labels:
        app: "aksexample-87a7"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "aksexample-87a7"