apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-nodejs
  labels:
    app: aks-nodejs
spec:
  selector:
    matchLabels:
      app: aks-nodejs
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aks-nodejs
    spec:
      containers:
      - name: aks-nodejs
        image: mohitp41/aks-node-intel:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "500m"