apiVersion: v1
kind: Service
metadata:
  name: aks-nodejs
  labels:
    app: aks-nodejs
spec:
  type: LoadBalancer
  selector:
    app: aks-nodejs
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000